---
title: STAT 4354 Homework 2
author: JaimeGoB
output: pdf_document
urlcolor: blue
geometry: "top = 1cm"
always_allow_html: yes
---

\begin{center}
Due date: Wednesday, February 17
\end{center}

```{R setup, include = FALSE}
knitr::opts_chunk$set(comment = NA, prompt = TRUE, collapse = TRUE)
```

**Submission instructions:**

  - This assignment is due to our grader, Zhiwei Zhen (zxz190002@utdallas.edu)
    by 11:59 pm, Wednesday, February 17. 
  - Please submit a `Rmd` file and a `pdf` file generated by R markdown.
  - Name your file `LastName4354hw2.pdf` and `LastName4354hw2.Rmd`, for example, `Chiou4354hw2.pdf` and `Chiou4354hw2.Rmd`.
  - The following submission policies will apply unless you have an emergency note:
      - Submission on Thursday, February 18, will be considered late and will be penalized (50\% penalty).
      - Submission after Thursday, February 18, will not be graded and be counted as a 0.
  - Please indicate by number which questions you are answering.
  - Please include a random seed if you use random number generators.
  - Start a problem in a new page, e.g., `\newpage`.

\newpage
**Questions:** 

### 1. (2 pts) The following codes gives a vector of 1's and 2's:
    ```{R}
c(1, 2, 1, 2, 1, 2, 1, 2, 1, 2)
rep(1:2, 5)
    ```
### Give two more approaches that return the same vectors of 1's and 2's without using the `c()` and the `rep()` function. \newline

Approach number 1 can be done using a list and appending a sequence of 1,2 five times.
```{r, echo=TRUE,include=TRUE}
list <- list()
for(i in 1:5){
  list <- append(list, 1:2)
}
unlist(list)
```
Approach number 2 can be done using replicate function with sequence function 5 times.
```{R}
array(replicate(n = 5, seq(1:2)))
```
\newpage

### 2. (2 pts) The following `R` codes are used to generate numerical vectors `x1`, `x2`, and `x3`, such that: 
### `median(x1)` = `mean(x1)`, 
### `median(x2)` > `mean(x2)`, and 
### `median(x3)` < `mean(x3)`.

```{R}
x1 <- x2 <- x3 <- 1:10; x2[5] <- x2[6]; x3[5] <- x3[4]
median(x1) == mean(x1)
median(x2) > mean(x2)
median(x3) < mean(x3)
```
### Create a new set of `x1`, `x2`, and `x3`, that satisfy these conditions. \newline

Creating a list with a sequence from 1 to 100. I slightly modified some values near the mean to satisfy conditions needed.
```{R}
#Create sequence 1 to 100
x1 <- x2 <- x3 <- 1:100; 
#Replace 1 with 60 (make median bigger than mean)
x2[1] <- x2[60]; 
#Replace 60 with 1 (make median smaller than mean)
x3[60] <- x3[1]
#Display Logic
median(x1) == mean(x1)
median(x2) > mean(x2)
median(x3) < mean(x3)
```

\newpage

### 3. (2 pts) Given a sample, $x_1, x_2, \ldots, x_n$, the sample variance is defined as
$$s^2 = \frac{\sum_{i = 1}^n(x_i - \bar x)^2}{n - 1}.$$

###  Write a `R` function that takes a numerical vector as the input and calculates the sample variance after outliers are removed. Name this function `var2()`. To receive full credit, print `var2(1:10)` and `var2(exp(1:10))`. \newline

The function declaration for sample variance is shown below:
Where x_i is the input vector.
```{R}
var2 <- function(x_i) {
  #variables needed for formula
  x_bar <- mean(x_i)
  n <- length(x_i)
  
#returning sample variance
return((sum((x_i - x_bar)^2)) / (n - 1) )
}
```
Output from sample variance function:
```{R}
var2(1:10)
var2(exp(1:10))
```

\newpage

###  4. (2 pts) In `R`, the largest integer is 
$$2^{31} - 1= 2147483647$$ See for example: 

    ```{R}
    str(.Machine$integer.max)
    str(.Machine$integer.max + 1L)
```
###  What is the largest possible (numerical) value in `R`? \newline

The biggest possible value a double in R can have is provided by the following equation:
$$ 2^{1023} \times (1 + (1 - 2^{-52})) \approx 1.7976931348623157 \times 10^{308}  $$
This can be verified by the output from R console:
```{R}
str(.Machine$double.xmax)
```

\newpage

###  5. (2 pts) What is the probability to observe exact 7 heads when a fair coin is tossed 10 times? 
###  The answer to this question is 11.72\%. Use the following steps to verify this answer. \newline

Before I proceed to answer the questions I will show that the math behind getting exactly 7 heads when tossing a fair coin 10 times. \newline\newline
Let H denote heads, T tails and S the sample space of a sequences of heads and tails.

S = {HHHHHHHHHH, 
     HHHHHHHHHT, 
     HHHHHHHHTH, 
     HHHHHHHHTT, 
     HHHHHHHTHH, 
     HHHHHHHTHT, 
     HHHHHHHTTH, 
     HHHHHHHTTT, 
     HHHHHHTHHH, 
     HHHHHHTHHT,
     ..........,
     TTTTTTTHTT, 
     TTTTTTTTHH, 
     TTTTTTTTHT, 
     TTTTTTTTTH, 
     TTTTTTTTTT}
     
The **binomial distribution** is frequently used to model the number of successes in a sample of size n drawn with replacement from a population of size N.

Using a binomial distribution we can see that:

- n = 10 trials

- p = 1/2 (fair coin with equally liked outcomes)

- k = 7 success (heads)

- n-k = failures (tails)

$$ \binom{n}{k}p^{k}(1-p)^{n-k} = \binom{10}{7} (\frac{1}{2})^{7} (\frac{1}{2})^{3} = \frac{15}{128} = .1172 \implies 11.72\%$$ 

### Step 1: Use the `sample()` function to mimic a sequence of ten coin tosses.

Using the sample function with values 0,1 we can sample with replacement 10 times to mimic a sequence of 10 coin tosses. This can be seen from output:

- 0 denotes tails 

- 1 denotes heads \newline
```{R}
number_of_coin_tosses = 10
ten_coin_tosses <- sample(0:1, number_of_coin_tosses, rep = T)
ten_coin_tosses
```

###    Step 2: Count the number of "heads" in Step 1. \newline
I counted the total number of heads using sum function. The results can be seen below: \newline
```{R}
sum(ten_coin_tosses)
```
\newpage

###    Step 3: Repeat Steps 1 and 2 1,000 times. \newline
Step 1 and Step 2 are combined for simplicity in the following r commands.

- Line 1: First tosses a fair coin 1 times and counts the number of heads. This is done 1000 times.

- Line 2: We combined all each different number of heads(1-10) together to get their counts.

- Line 3: Display distribution of number of heads. \newline
```{R}
trials = 1000
one_thousand_ten_coin_tosses <- replicate(trials, 
                                          sum(sample(0:1, number_of_coin_tosses, rep = T)))
one_thousand_ten_coin_tosses <- table(one_thousand_ten_coin_tosses)
one_thousand_ten_coin_tosses
```
###    The average number of "heads" find in Step 3 provides a valid approximation to the probability to observe exact 7 heads when a fair coin is tossed 10 times. Report your average in Step 3. \newline

**Using a binomial distribution** I showed that getting exactly 7 heads when tossing a fair coin 10 times will be .1172 or 11.72%. 

According to **Law of Large Numbers**:
$$ \overline x \to \mu$$ as $$ n \to \infty $$
We can see as the number of trials gets larger (trials = 1000) we approximate the mean. \newline
```{R}
sample_mean <- one_thousand_ten_coin_tosses['7'] / trials
sample_mean
```

From r output above it is evident to see that: \newline
\texttt{sample mean $\approx$ .1172}